
[2025-09-09 23:24:34.216116] >>> python download_from_drive.py
Traceback (most recent call last):
  File "C:\Users\wator\Documents\AIECO\COAI\download_from_drive.py", line 67, in <module>
    download_latest_file()
  File "C:\Users\wator\Documents\AIECO\COAI\download_from_drive.py", line 34, in download_latest_file
    creds = authenticate()
            ^^^^^^^^^^^^^^
  File "C:\Users\wator\Documents\AIECO\COAI\download_from_drive.py", line 26, in authenticate
    flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wator\AppData\Local\Programs\Python\Python311\Lib\site-packages\google_auth_oauthlib\flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
